name: Schedule Workflow Dispatch
on:
  schedule:
    - cron: '*/5 * * * *' # every 5 mins
  workflow_dispatch:
  
concurrency:
  group: schedule${{ github.event.inputs.date }}
  cancel-in-progress: true

jobs:
  schedule:
    name: Schedule
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: echo "Hello, Commit happened successfully"	
